---
version: '3.9'
services:
  javaprod:
    build:
      context: .
    image: alpine:javarun
    ports:
      - "8085:8080"
    volumes:
      - ./java:/opt/java
      - ./tomcat:/opt/tomcat
      - ./webapps:/opt/tomcat/webapps/

#  javabuilder:
#    env_file:
#      - ./.env
#    build:
#      context: ./javabuild
#    image: debian:javabuilder
#    volumes:
#      - ./webapps:/opt/webapps
#      - ./javabuild/log:/opt/log