---
version: '3.9'
services:
  javaprod:
    build:
      context: .
    image: alpine:javarun
    volumes:
      - ./webapps:/opt/webapps

#  javabuilder:
#    env_file:
#      - ./.env
#    build:
#      context: ./javabuild
#    image: debian:javabuilder
#    volumes:
#      - ./webapps:/opt/webapps
#      - ./javabuild/log:/opt/log