---
version: '3.9'
services:
  javabuilder:
    env_file:
      - ./.env
    build:
      context: ./javabuild
    image: debian:javabuilder
    volumes:
      - ./webapps:/opt/webapps
      - ./javabuild/log:/opt/log