---
version: '3.9'
services:
  javabuilder:
    environment:
      GHUB_LINK: https://github.com/MithunTechnologiesDevOps/java-web-app-docker.git
    build:
      context: ./javabuild
    image: debian:javabuilder
    volumes:
      - ./webapps:/opt/webapps
      - ./javabuild/log:/opt/log