---
version: '3.9'
services:
  javabuilder:
    build:
      context: ./javabuild
    image: debian:maven
    env_file:
      - ./javabuild/.env
    volumes:
      - ./javabuild/maven:/opt/maven
      - ./webapps:/opt/webapps
      - ./javabuild/java:/opt/java