---
version: '3.9'
services:
  javabuilder:
    env_file:
      - "./javabuild/.env"
    build:
      context: ./javabuild
    volumes:
      - "./javabuild/maven:/opt/maven"
      - "./webapps:/opt/webapps"
      - "./javabuild/java:/opt/java"